name: PlayerMarkers
version: 0.3.0
decsription: Generates Markers on an Overviewer generated map
author: 1am3r, revised by braste
website: http://braste.github.com/PlayerMarkers/
dev-url: http://dev.bukkit.org/server-mods/mapmarkers/
main: de.braste.PlayerMarkers
