name: PlayerMarkers
version: 0.3.1-SNAPSHOT (CraftBukkit 1.7.9-R0.2)
decsription: Generates Markers on an Overviewer generated map
author: 1am3r, revised by braste
website: http://braste.github.com/PlayerMarkers/
dev-url: http://dev.bukkit.org/server-mods/mapmarkers/
main: de.braste.SPfB.PlayerMarkers
